export const data = [
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
   {
      id: "728ed52f",
      type: "Comprovante de estudante",
      studant: "Jacinto Pinto",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52a",
      type: "Comprovante de estudante",
      studant: "Thomar Turbando",
      createdAt: new Date().toLocaleDateString(),
      status: "in progress",
   },
   {
      id: "728ed52b",
      type: "Comprovante de estudante",
      studant: "Paula Tejando",
      createdAt: new Date().toLocaleDateString(),
      status: "success",
   },
];